<option value="">Select Bank Name</option>
<option value="Allahabad Bank">Allahabad Bank</option>
<option value="Andhra Bank">Andhra Bank</option>
<option value="Axis Bank">Axis Bank</option>
<option value="Bank of India">Bank of India</option>
<option value="Bank of Baroda">Bank of Baroda</option>
<option value="Bank of Maharashtra">Bank of Maharashtra</option>
<option value="Bandhan Bank">Bandhan Bank</option>
<option value="Bharatiya Mahila Bank">Bharatiya Mahila Bank</option>
<option value="Canara Bank">Canara Bank</option>
<option value="Central Bank of India">Central Bank of India</option>
<option value="Citibank">Citibank</option>
<option value="Corporation Bank">Corporation Bank</option>
<option value="Catholic Syrian Bank">Catholic Syrian Bank</option>
<option value="City Union Bank">City Union Bank</option>
<option value="Dena Bank">Dena Bank</option>
<option value="Dhanlaxmi Bank">Dhanlaxmi Bank</option>
<option value="DCB Bank">DCB Bank</option>
<option value="Federal Bank">Federal Bank</option>
<option value="HDFC Bank">HDFC Bank</option>
<option value="Indian Bank">Indian Bank</option>
<option value="Indian Overseas Bank">Indian Overseas Bank</option>
<option value="IDBI Bank">IDBI Bank</option>
<option value="ICICI Bank">ICICI Bank</option>
<option value="IDFC Bank">IDFC Bank</option>
<option value="IndusInd Bank">IndusInd Bank</option>
<option value="Jammu and Kashmir Bank">Jammu and Kashmir Bank</option>
<option value="Karnataka Bank">Karnataka Bank</option>
<option value="Karur Vysya Bank">Karur Vysya Bank</option>
<option value="Kotak Mahindra Bank">Kotak Mahindra Bank</option>
<option value="Lakshmi Vilas Bank">Lakshmi Vilas Bank</option>
<option value="Nainital Bank">Nainital Bank</option>
<option value="Oriental Bank of Commerce">Oriental Bank of Commerce</option>
<option value="Punjab & Sindh Bank">Punjab & Sindh Bank</option>
<option value="Punjab National Bank">Punjab National Bank</option>
<option value="RBL Bank">RBL Bank</option>
<option value="State Bank of India"> State Bank of India</option>
<option value="State Bank of Bikaner and Jaipur"> State Bank of Bikaner and Jaipur</option>
<option value="State Bank of Hyderabad">State Bank of Hyderabad</option>
<option value="State Bank of Mysore">State Bank of Mysore</option>
<option value="State Bank of Patiala">State Bank of Patiala</option>
<option value="State Bank of Travancore">State Bank of Travancore</option>
<option value="State Bank of Sikkim">State Bank of Sikkim</option>
<option value="South Indian Bank">South Indian Bank</option>
<option value="Syndicate Bank">Syndicate Bank</option>
<option value="Tamilnad Mercantile Bank Limited">Tamilnad Mercantile Bank Limited</option>
<option value="UCO Bank">UCO Bank</option>
<option value="Union Bank of India">Union Bank of India</option>
<option value="United Bank of India">United Bank of India</option>
<option value="Vijaya Bank">Vijaya Bank</option>
<option value="Yes Bank">Yes Bank</option>