CREATE TABLE `employee_work_details` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `employee_name` varchar(20) NOT NULL,
  `employee_lastname` varchar(20) NOT NULL,
  `employee_doj` date NOT NULL DEFAULT '0000-00-00',
  `employee_confirmation_date` date NOT NULL DEFAULT '0000-00-00',
  `employee_probation_period` varchar(20) NOT NULL COMMENT 'probt period',
  `status_id` varchar(20) NOT NULL COMMENT 'job status',
  `branch_id` varchar(20) NOT NULL COMMENT 'branch',
  `department_id` varchar(20) NOT NULL COMMENT 'dept',
  `team_id` varchar(20) DEFAULT 'TM0001',
  `transfer_id` varchar(20) NOT NULL DEFAULT 'CREATION' COMMENT 'currentLeavaloftransfer',
  `promotion_id` varchar(20) NOT NULL DEFAULT 'CREATION' COMMENT 'current level of promotion',
  `designation_id` varchar(20) NOT NULL COMMENT 'desgn',
  `design_effects_from` date NOT NULL DEFAULT '0000-00-00',
  `branch_effects_from` date NOT NULL DEFAULT '0000-00-00',
  `employee_reporting_person` varchar(20) NOT NULL COMMENT 'reporting to',
  `employee_emp_pf_no` varchar(30) DEFAULT NULL COMMENT 'emp pf',
  `employee_emp_uan_no` varchar(20) DEFAULT NULL COMMENT 'emp uan',
  `employee_emp_esi_no` varchar(20) DEFAULT NULL COMMENT 'emp id suff',
  `payment_mode_id` varchar(20) NOT NULL,
  `notice_period` varchar(20) NOT NULL,
  `notice_date` date DEFAULT '0000-00-00',
  `off_ltr_proof` varchar(50) DEFAULT 'Nil',
  `confirm_ltr_proof` varchar(50) DEFAULT 'Nil',
  `contract_ltr_proof` varchar(20) DEFAULT 'Nil',
  `shift_id` varchar(20) DEFAULT 'Nil',
  `weekend_id` varchar(20) DEFAULT 'Nil',
  `confirm_ltr_issue_dt` varchar(10) DEFAULT 'Nil',
  `contract_ltr_issue_dt` varchar(10) DEFAULT 'Nil',
  `off_ltr_issue_dt` varchar(10) DEFAULT 'Nil',
  `enabled` tinyint(1) NOT NULL,
  `payroll_enabled` tinyint(4) NOT NULL DEFAULT '1',
  `depart_effects_from` date DEFAULT '0000-00-00',
  `designation_change_reason` varchar(200) DEFAULT NULL,
  `department_change_reason` varchar(200) DEFAULT NULL,
  `branch_change_reason` varchar(200) DEFAULT NULL,
  `team_change_reason` varchar(200) DEFAULT NULL,
  `job_status_change_reason` varchar(200) DEFAULT NULL,
  `shift_change_reason` varchar(200) DEFAULT NULL,
  `team_effects_from` date DEFAULT '0000-00-00',
  `job_status_effects_from` date DEFAULT '0000-00-00',
  `shift_effects_from` date DEFAULT '0000-00-00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(50) DEFAULT NULL,
  `dateofexit` date DEFAULT '0000-00-00',
  `company_id` varchar(20) DEFAULT NULL,
  `exempt_attn` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`,`employee_id`),
  UNIQUE KEY `employee_id` (`employee_id`),
  KEY `fk_department` (`department_id`),
  KEY `fk_designation` (`designation_id`),
  KEY `fk_branch` (`branch_id`),
  KEY `fk_job_status` (`status_id`),
  KEY `fk_payment_modes` (`payment_mode_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='emp work det';

CREATE TABLE `asset_requests` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `request_id` varchar(20) NOT NULL,
  `employee_id` varchar(30) NOT NULL,
  `asset_type` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil' COMMENT 'Hotel, Travel, Others',
  `from_date` date NOT NULL,
  `to_date` date NOT NULL,
  `purpose` varchar(100) CHARACTER SET latin1 NOT NULL,
  `description` varchar(150) CHARACTER SET latin1 NOT NULL,
  `status` varchar(20) CHARACTER SET latin1 DEFAULT 'P',
  `asset_id` varchar(30) CHARACTER SET latin1 DEFAULT NULL,
  `issue_on` date DEFAULT NULL,
  `issue_notes` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `return_on` date DEFAULT NULL,
  `return_notes` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `asset_requests_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='salary payment modes';

CREATE TABLE `assets` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `asset_id` varchar(30) NOT NULL,
  `asset_name` varchar(50) NOT NULL,
  `asset_type` varchar(20) NOT NULL DEFAULT 'Nil' COMMENT 'Hotel, Travel, Others',
  `asset_condition` varchar(20) NOT NULL,
  `purchase_date` date NOT NULL,
  `cost` varchar(50) NOT NULL,
  `serial_number` varchar(50) NOT NULL,
  `manufacturer` varchar(50) NOT NULL,
  `warranty_date` date NOT NULL,
  `model` varchar(50) NOT NULL,
  `asset_status` varchar(20) NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='salary payment modes';

CREATE TABLE `claim_mapping` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `claim_rule_id` varchar(30) NOT NULL,
  `applicable_for` char(1) NOT NULL COMMENT 'B,D,F,E',
  `applicable_id` varchar(30) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='salary payment modes';

CREATE TABLE `claim_rules` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `claim_rule_id` varchar(30) NOT NULL,
  `claim_name` varchar(30) NOT NULL,
  `alias_name` varchar(20) NOT NULL DEFAULT 'Nil',
  `category_type` varchar(20) NOT NULL DEFAULT 'Nil' COMMENT 'Hotel, Travel, Others',
  `sub_type` varchar(20) DEFAULT 'Nil',
  `class` varchar(20) DEFAULT 'Nil',
  `amount_from` int(20) DEFAULT NULL,
  `amount_to` int(20) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`,`claim_rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='salary payment modes';

CREATE TABLE `claims` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `claim_id` varchar(30) NOT NULL,
  `employee_id` varchar(30) CHARACTER SET utf8 NOT NULL,
  `claim_rule_id` varchar(30) NOT NULL,
  `purpose` varchar(50) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  `from_date` date NOT NULL,
  `to_date` date DEFAULT NULL,
  `amount` decimal(20,2) NOT NULL DEFAULT '0.00',
  `reference_no` varchar(30) DEFAULT NULL,
  `bill_url` varchar(300) NOT NULL,
  `status` char(1) DEFAULT 'P',
  `amount_approved` decimal(20,2) NOT NULL DEFAULT '0.00',
  `approved_on` date NOT NULL DEFAULT '0000-00-00',
  `admin_remarks` varchar(100) DEFAULT NULL,
  `processed_on` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`,`claim_rule_id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `claims_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='claims claimed by employee';

CREATE TABLE `comp_promotions_increments` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `action_id` varchar(20) NOT NULL,
  `action_for` char(1) NOT NULL,
  `affected_ids` varchar(100) NOT NULL,
  `action_effects_from` date NOT NULL DEFAULT '0000-00-00',
  `promoted_desig_id` varchar(20) NOT NULL DEFAULT 'NA',
  `incremented_amount` varchar(30) NOT NULL DEFAULT '0|A',
  `employees_affected` int(10) NOT NULL DEFAULT '0' COMMENT 'number of employees affected',
  `performed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `performed_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `action_id` (`action_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='increments and promotions performed in company';

CREATE TABLE `comp_transfers` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `action_id` varchar(20) NOT NULL,
  `action_for` char(1) NOT NULL,
  `affected_ids` varchar(100) NOT NULL,
  `action_effects_from` date NOT NULL DEFAULT '0000-00-00',
  `transferred_branch_id` varchar(20) NOT NULL,
  `employees_affected` int(10) NOT NULL DEFAULT '0' COMMENT 'number of employees affected',
  `is_teamTrans` tinyint(4) DEFAULT NULL,
  `performed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `performed_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='increments and promotions performed in company';

CREATE TABLE `company_allowance_slabs` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `slab_id` varchar(30) NOT NULL,
  `slab_name` varchar(30) NOT NULL,
  `slab_type` char(5) NOT NULL,
  `basic` varchar(20) DEFAULT '0|P',
  `c_hra` varchar(20) DEFAULT '0|P',
  `min_salary_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `enabled` tinyint(1) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slab_id` (`slab_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='slab for allowances';

CREATE TABLE `company_branch` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `branch_id` varchar(30) NOT NULL,
  `branch_name` varchar(50) NOT NULL,
  `branch_addr` varchar(60) NOT NULL,
  `city_pin` int(20) NOT NULL,
  `pt_city_id` varchar(30) NOT NULL,
  `pt_no` varchar(30) NOT NULL,
  `esi_no` varchar(30) NOT NULL,
  `pf_no` varchar(30) NOT NULL,
  `tan_no` varchar(30) NOT NULL,
  `resp_person_emp_id` varchar(30) NOT NULL,
  `state` varchar(20) DEFAULT NULL,
  `city` varchar(20) DEFAULT NULL,
  `enabled` tinyint(3) NOT NULL DEFAULT '1',
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`branch_id`),
  UNIQUE KEY `branch_id` (`branch_id`),
  UNIQUE KEY `unique_branch` (`branch_name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `company_deductions` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `deduction_id` varchar(50) CHARACTER SET latin1 NOT NULL,
  `alias_name` varchar(30) CHARACTER SET latin1 NOT NULL,
  `is_both_contribution` tinyint(1) NOT NULL DEFAULT '0',
  `is_admin_charges` tinyint(1) NOT NULL DEFAULT '0',
  `employee_share` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '0|P',
  `employer_share` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '0|A',
  `admin_charges` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '0|A',
  `deduce_in` varchar(200) CHARACTER SET latin1 NOT NULL DEFAULT 'GROSS',
  `payment_to` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `frequency` char(2) CHARACTER SET latin1 NOT NULL DEFAULT 'M',
  `max_employee_share` varchar(20) DEFAULT '0',
  `cal_exemption` varchar(20) DEFAULT '0',
  `max_employer_share` varchar(20) DEFAULT '0',
  `due_in` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`deduction_id`),
  UNIQUE KEY `deduction_id` (`deduction_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='leave rules';

CREATE TABLE `company_departments` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `department_id` varchar(20) NOT NULL,
  `department_name` varchar(50) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`,`department_id`),
  UNIQUE KEY `department_id` (`department_id`),
  UNIQUE KEY `unique_dept` (`department_name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `company_designations` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `designation_id` varchar(20) NOT NULL,
  `designation_name` varchar(50) NOT NULL,
  `designation_hierarchy` int(20) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`designation_id`),
  UNIQUE KEY `designation_id` (`designation_id`),
  UNIQUE KEY `unique_desig` (`designation_name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `company_details` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `company_id` varchar(20) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `company_type` varchar(20) NOT NULL COMMENT 'company type of incorp',
  `company_user_name` varchar(20) NOT NULL DEFAULT 'Nil',
  `company_doi` date NOT NULL DEFAULT '0000-00-00',
  `company_logo` varchar(50) NOT NULL COMMENT 'logo url of company',
  `company_cin_no` varchar(20) NOT NULL COMMENT 'cin number',
  `company_emp_id_prefix` varchar(10) NOT NULL DEFAULT '0' COMMENT 'emp id pref',
  `company_emp_id_suffix` varchar(10) NOT NULL DEFAULT '0' COMMENT 'emp id suff',
  `current_payroll_month` date NOT NULL DEFAULT '0000-00-00',
  `company_build_name` varchar(50) NOT NULL COMMENT 'addr',
  `company_street` varchar(50) NOT NULL COMMENT 'addr',
  `company_area` varchar(30) NOT NULL COMMENT 'addr',
  `company_city` varchar(30) NOT NULL COMMENT 'addr',
  `company_pin_code` int(6) NOT NULL COMMENT 'addr',
  `company_website` varchar(50) NOT NULL,
  `company_state` varchar(30) NOT NULL COMMENT 'addr',
  `company_phone` varchar(20) NOT NULL COMMENT 'phone number',
  `company_mobile` varchar(20) NOT NULL COMMENT 'mobile number',
  `company_email` varchar(40) NOT NULL COMMENT 'email id of company',
  `company_pin` int(4) DEFAULT NULL COMMENT 'the four number . for access',
  `company_pan_no` varchar(10) DEFAULT 'NA' COMMENT 'pan number',
  `company_tan_pattern` varchar(20) DEFAULT 'C',
  `company_tan_no` varchar(20) DEFAULT 'NA' COMMENT 'tan number',
  `company_epf_pattern` varchar(20) DEFAULT 'C' COMMENT 'epf pattrn',
  `company_epf_no` varchar(30) DEFAULT 'NA' COMMENT 'epf num',
  `company_esi_pattern` varchar(20) DEFAULT 'C' COMMENT 'esi pattrn',
  `company_esi_no` varchar(30) DEFAULT 'NA' COMMENT 'esi num',
  `company_resp1_name` varchar(30) NOT NULL COMMENT 'resp person 1',
  `hr_1username` varchar(20) NOT NULL,
  `company_resp1_desgn` varchar(30) NOT NULL COMMENT 'resp person 1',
  `company_resp1_phone` varchar(20) NOT NULL COMMENT 'resp person 1',
  `company_resp1_email` varchar(40) NOT NULL COMMENT 'resp person 1',
  `hr_2username` varchar(20) NOT NULL DEFAULT '20',
  `company_resp2_name` varchar(30) NOT NULL COMMENT 'resp person 2',
  `company_resp2_desgn` varchar(30) NOT NULL COMMENT 'resp person 2',
  `company_resp2_phone` varchar(20) NOT NULL COMMENT 'resp person 2',
  `company_resp2_email` varchar(40) NOT NULL COMMENT 'resp person 2',
  `approval_remarks` varchar(50) DEFAULT NULL,
  `info_flag` varchar(20) NOT NULL DEFAULT 'A',
  `leave_based_on` varchar(20) DEFAULT NULL,
  `email_method` enum('phpmail','smtp') DEFAULT 'phpmail',
  `email_notify` enum('yes','no') DEFAULT 'no',
  `salary_days` varchar(2) DEFAULT 'ad',
  `attendance_period_sdate` varchar(2) DEFAULT '01',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `company_job_statuses` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `status_id` varchar(20) NOT NULL,
  `status_name` varchar(30) NOT NULL,
  `status_comments` varchar(200) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`status_id`),
  UNIQUE KEY `status_id` (`status_id`),
  UNIQUE KEY `unique_jobsts` (`status_name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='Job Statuses for Company';

CREATE TABLE `company_leave_rules` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `leave_rule_id` varchar(20) NOT NULL,
  `rule_name` varchar(30) NOT NULL,
  `alias_name` varchar(30) NOT NULL,
  `allot_from` varchar(10) NOT NULL DEFAULT 'JD',
  `type` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'Y',
  `days_count` decimal(10,2) NOT NULL DEFAULT '0.00',
  `max_combinable` decimal(10,2) NOT NULL DEFAULT '0.00',
  `pro_rata_basis` tinyint(1) NOT NULL DEFAULT '1',
  `allot_on` char(2) CHARACTER SET latin1 NOT NULL DEFAULT 'AD',
  `round_off` char(2) CHARACTER SET latin1 NOT NULL DEFAULT 'LH',
  `calculation_on` char(2) CHARACTER SET latin1 NOT NULL DEFAULT 'PM',
  `carry_forward` tinyint(1) NOT NULL DEFAULT '0',
  `max_cf_days` int(20) NOT NULL DEFAULT '0',
  `remain_cf` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'L',
  `is_encashable` tinyint(1) NOT NULL DEFAULT '0',
  `max_enc_days` int(20) NOT NULL DEFAULT '0',
  `remain_enc` char(2) CHARACTER SET latin1 NOT NULL DEFAULT 'L',
  `encashable_on` char(1) CHARACTER SET latin1 DEFAULT NULL,
  `enc_salary` varchar(20) NOT NULL DEFAULT '0',
  `leave_in_middle` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'B',
  `leave_in_preceeding` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'N',
  `leave_in_succeeding` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'N',
  `club_with` varchar(100) NOT NULL DEFAULT 'N',
  `applicable_to` varchar(30) NOT NULL DEFAULT 'NIL',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `min_monthly_contrib` tinyint(1) DEFAULT '0',
  `leave_per_month` tinyint(1) DEFAULT '0',
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='leave rules';

CREATE TABLE `company_loan_mapping` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `loan_id` varchar(20) CHARACTER SET latin1 NOT NULL,
  `loan_amount` varchar(20) CHARACTER SET latin1 NOT NULL,
  `no_installment` varchar(20) CHARACTER SET latin1 NOT NULL,
  `emi_amount` varchar(20) CHARACTER SET latin1 NOT NULL,
  `issued_on` date NOT NULL DEFAULT '0000-00-00',
  `starts_from` date NOT NULL DEFAULT '0000-00-00',
  `closing_balance` varchar(20) CHARACTER SET latin1 NOT NULL,
  `closing_date` date NOT NULL DEFAULT '0000-00-00',
  `remaining_installments` varchar(20) CHARACTER SET latin1 NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `company_loan_mapping_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='company_loan_mapping';

CREATE TABLE `company_loans` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `loan_id` varchar(20) CHARACTER SET latin1 NOT NULL,
  `loan_name` varchar(30) CHARACTER SET latin1 NOT NULL,
  `alias_name` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `loan_category` varchar(30) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `interest_rate` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `sbi_interest_rate` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'Nil',
  `enabled` tinyint(1) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='salary payment modes';

CREATE TABLE `company_login_details` (
  `id` int(15) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(20) NOT NULL,
  `password` varchar(100) NOT NULL,
  `emp_id` varchar(30) NOT NULL DEFAULT 'Nil',
  `login_privilage` varchar(20) NOT NULL,
  `email` varchar(70) DEFAULT NULL,
  `send_email` tinyint(1) DEFAULT '0',
  `last_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='login details for company';

CREATE TABLE `company_pay_structure` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `pay_structure_id` varchar(30) NOT NULL,
  `display_name` varchar(40) NOT NULL,
  `type` char(2) CHARACTER SET latin1 NOT NULL,
  `sort_order` int(20) NOT NULL,
  `display_flag` tinyint(1) DEFAULT '0',
  `alias_name` varchar(12) DEFAULT NULL,
  `updated_by` varchar(20) DEFAULT NULL,
  `exemption_mapped_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `exemption_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pay_structure_id` (`pay_structure_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='pay structure of the company allowances and deductions';

	CREATE TABLE `company_payment_modes` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `payment_mode_id` varchar(30) NOT NULL,
  `payment_mode_name` varchar(30) NOT NULL,
  `bank_name` varchar(20) NOT NULL DEFAULT 'Nil',
  `bank_ac_no` varchar(20) NOT NULL DEFAULT 'Nil',
  `bank_branch` varchar(20) NOT NULL DEFAULT 'Nil',
  `bank_ifsc` varchar(20) NOT NULL DEFAULT 'Nil',
  `enabled` tinyint(1) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `account_type` varchar(20) NOT NULL,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`,`payment_mode_id`),
  UNIQUE KEY `payment_mode_id` (`payment_mode_id`),
  UNIQUE KEY `unique_payment` (`payment_mode_name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='salary payment modes';

CREATE TABLE `company_shifts` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `shift_id` varchar(20) NOT NULL,
  `shift_name` varchar(30) NOT NULL,
  `start_time` varchar(20) NOT NULL DEFAULT '00:00',
  `end_time` varchar(20) NOT NULL DEFAULT '00:00',
  `grace_inTime` varchar(20) NOT NULL DEFAULT '00:00',
  `grace_outTime` varchar(20) NOT NULL DEFAULT '00:00',
  `early_start` varchar(20) NOT NULL DEFAULT '00:00',
  `late_end` varchar(20) NOT NULL DEFAULT '00:00',
  `min_hrs_ot` varchar(20) NOT NULL DEFAULT '00:00',
  `min_hrs_half_day` varchar(20) NOT NULL DEFAULT '00:00:00',
  `min_hrs_full_day` varchar(20) NOT NULL DEFAULT '00:00:00',
  `shift_hrs` varchar(20) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL,
  `is_day` varchar(2) DEFAULT '1',
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='leave rules';

CREATE TABLE `emp_branch_history` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `transfer_id` varchar(20) CHARACTER SET latin1 DEFAULT 'NA',
  `branch_id` varchar(20) CHARACTER SET latin1 NOT NULL,
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `effects_upto` date NOT NULL DEFAULT '0000-00-00',
  `branch_change_reason` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `emp_branch_history_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='increments and promotions performed in company';

CREATE TABLE `emp_designation_history` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `promotion_id` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'NA',
  `designation_id` varchar(20) CHARACTER SET latin1 NOT NULL,
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `effects_upto` date NOT NULL DEFAULT '0000-00-00',
  `designation_change_reason` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `emp_designation_history_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='increments and promotions performed in company';

CREATE TABLE `emp_leave_account` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `year` int(11) NOT NULL DEFAULT '0',
  `leave_rule_id` varchar(20) NOT NULL,
  `opening_bal` decimal(10,2) NOT NULL DEFAULT '0.00',
  `allotted` decimal(10,2) NOT NULL DEFAULT '0.00',
  `availed` decimal(10,2) NOT NULL DEFAULT '0.00',
  `encashed` decimal(10,2) NOT NULL DEFAULT '0.00',
  `adjusted` decimal(10,2) NOT NULL DEFAULT '0.00',
  `lapsed` decimal(10,2) NOT NULL DEFAULT '0.00',
  `is_leavecredited` tinyint(1) NOT NULL DEFAULT '0',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`year`,`employee_id`,`leave_rule_id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `emp_leave_account_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='attendance';

CREATE TABLE `emp_montly_attendance` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `year` varchar(20) CHARACTER SET latin1 NOT NULL,
  `month_year` date NOT NULL DEFAULT '0000-00-00',
  `compoff` decimal(10,2) DEFAULT '0.00',
  `remarks` varchar(100) DEFAULT NULL,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`year`,`employee_id`,`month_year`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `emp_montly_attendance_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='attendance';

CREATE TABLE `emp_notice_period` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `notice_id` varchar(30) NOT NULL,
  `employee_id` varchar(30) NOT NULL,
  `notice_date` date NOT NULL DEFAULT '0000-00-00',
  `last_working_date` date NOT NULL DEFAULT '0000-00-00',
  `reason` varchar(50) DEFAULT NULL,
  `letter_text` text CHARACTER SET latin1,
  `remark` varchar(20) DEFAULT NULL,
  `process_type` char(2) CHARACTER SET latin1 DEFAULT NULL,
  `processed_on` date DEFAULT '0000-00-00',
  `status` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'P',
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `emp_notice_period_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='noice period applied by employees';

CREATE TABLE `emp_work_history` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `company_name` varchar(50) CHARACTER SET latin1 NOT NULL,
  `from` varchar(20) CHARACTER SET latin1 NOT NULL,
  `to` varchar(30) CHARACTER SET latin1 NOT NULL,
  `designation` varchar(30) CHARACTER SET latin1 NOT NULL,
  `ctc` int(10) NOT NULL,
  `location` varchar(20) DEFAULT NULL,
  `contact_email` varchar(70) DEFAULT NULL,
  `prev_reporting_manager` varchar(20) DEFAULT NULL,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `emp_work_history_ibfk_1` (`employee_id`),
  CONSTRAINT `emp_work_history_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `employee_income_tax` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `year` int(11) NOT NULL,
  `prev_earnings_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `perqs` decimal(15,2) NOT NULL DEFAULT '0.00',
  `house_prop_inc` decimal(15,2) NOT NULL DEFAULT '0.00',
  `other_income` decimal(15,2) NOT NULL DEFAULT '0.00',
  `total_inc` decimal(15,2) NOT NULL DEFAULT '0.00',
  `exe_hra` decimal(15,2) NOT NULL DEFAULT '0.00',
  `exe_lta` decimal(10,2) NOT NULL DEFAULT '0.00',
  `exe_oth` decimal(15,2) NOT NULL DEFAULT '0.00',
  `yearly_gross` decimal(15,2) DEFAULT NULL,
  `gti` decimal(15,2) NOT NULL DEFAULT '0.00',
  `taxon_employment` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT 'pt',
  `epf_employee` decimal(15,2) DEFAULT NULL,
  `epf_employer` decimal(15,2) DEFAULT NULL,
  `ded_80c` decimal(15,2) NOT NULL DEFAULT '0.00',
  `ded_80d` decimal(15,2) NOT NULL DEFAULT '0.00',
  `ded_80e` decimal(15,2) NOT NULL DEFAULT '0.00',
  `ded_80g` decimal(15,2) NOT NULL DEFAULT '0.00',
  `ded_other` decimal(15,2) NOT NULL DEFAULT '0.00',
  `taxable_inc` decimal(15,2) NOT NULL DEFAULT '0.00',
  `tax` decimal(15,2) NOT NULL DEFAULT '0.00',
  `ec` decimal(15,2) NOT NULL DEFAULT '0.00',
  `shec` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_tax_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `surcharge` decimal(10,2) NOT NULL DEFAULT '0.00',
  `tax_paid` decimal(10,2) NOT NULL DEFAULT '0.00',
  `relief` decimal(10,2) NOT NULL DEFAULT '0.00',
  `rebate` decimal(10,2) NOT NULL DEFAULT '0.00',
  `old_tax_paid` decimal(10,2) DEFAULT '0.00',
  `tax_payable` decimal(15,2) NOT NULL DEFAULT '0.00',
  `tds` decimal(15,2) NOT NULL DEFAULT '0.00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`year`,`employee_id`),
  KEY `employee_income_tax_ibfk_1` (`employee_id`),
  CONSTRAINT `employee_income_tax_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='emp income tax';

CREATE TABLE `employee_it_declaration` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `year` int(11) NOT NULL,
  `prev_emp_code` varchar(20) DEFAULT NULL,
  `prev_employer_name` varchar(30) DEFAULT NULL,
  `prev_employer_tan` varchar(30) DEFAULT NULL,
  `prev_employer_proof` varchar(100) DEFAULT NULL,
  `prev_earnings_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_earnings_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_tax_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_tax_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_pt_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_pt_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_pf_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_pf_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `prev_emp_remarks` varchar(100) DEFAULT NULL,
  `owner1_name` varchar(50) DEFAULT NULL,
  `owner1_addr` varchar(200) DEFAULT NULL,
  `owner1_pan` varchar(30) DEFAULT 'Nil',
  `owner1_proof` varchar(100) DEFAULT 'Nil',
  `owner2_name` varchar(50) DEFAULT 'Nil',
  `owner2_addr` varchar(200) DEFAULT 'Nil',
  `owner2_pan` varchar(30) DEFAULT 'Nil',
  `owner2_proof` varchar(100) DEFAULT 'Nil',
  `apr_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `apr_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `apr_proof` varchar(100) DEFAULT 'Nil',
  `may_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `may_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `may_proof` varchar(100) DEFAULT 'Nil',
  `jun_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `jun_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `jun_proof` varchar(100) DEFAULT 'Nil',
  `jul_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `jul_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `jul_proof` varchar(100) DEFAULT 'Nil',
  `aug_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `aug_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `aug_proof` varchar(100) DEFAULT 'Nil',
  `sep_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `sep_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `sep_proof` varchar(100) DEFAULT 'Nil',
  `oct_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `oct_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `oct_proof` varchar(100) DEFAULT 'Nil',
  `nov_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `nov_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `nov_proof` varchar(100) DEFAULT 'Nil',
  `dec_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `dec_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `dec_proof` varchar(100) DEFAULT 'Nil',
  `jan_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `jan_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `jan_proof` varchar(100) DEFAULT 'Nil',
  `feb_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `feb_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `feb_proof` varchar(100) DEFAULT 'Nil',
  `mar_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `mar_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `mar_proof` varchar(100) DEFAULT 'Nil',
  `rent_remarks` varchar(100) DEFAULT 'Nil',
  `medical_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `medical_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `medical_remarks` varchar(100) DEFAULT 'Nil',
  `medical_proof` varchar(100) DEFAULT 'Nil',
  `lta_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `lta_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `lta_remarks` varchar(100) DEFAULT 'Nil',
  `lta_proof` varchar(100) DEFAULT 'Nil',
  `others_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `others_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `others_remarks` varchar(100) DEFAULT 'Nil',
  `others_proof` varchar(100) DEFAULT 'Nil',
  `80c_fd_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_fd_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_fd_remarks` varchar(100) DEFAULT 'Nil',
  `80c_fd_proof` varchar(100) DEFAULT 'Nil',
  `80c_tution_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_tution_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_tution_remarks` varchar(100) DEFAULT 'Nil',
  `80c_tution_proof` varchar(100) DEFAULT 'Nil',
  `80c_nsc_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_nsc_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_nsc_remarks` varchar(100) DEFAULT 'Nil',
  `80c_nsc_proof` varchar(100) DEFAULT 'Nil',
  `80c_sukanya_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_sukanya_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_sukanya_remarks` varchar(100) DEFAULT 'Nil',
  `80c_sukanya_proof` varchar(100) DEFAULT 'Nil',
  `80c_inf_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_inf_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_inf_remarks` varchar(100) DEFAULT 'Nil',
  `80c_inf_proof` varchar(100) DEFAULT 'Nil',
  `80c_vpf_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_vpf_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_vpf_remarks` varchar(100) DEFAULT 'Nil',
  `80c_vpf_proof` varchar(100) DEFAULT 'Nil',
  `80c_repa_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_repa_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_repa_remarks` varchar(100) DEFAULT 'Nil',
  `80c_repa_proof` varchar(100) DEFAULT 'Nil',
  `80c_lic_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_lic_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_lic_remarks` varchar(100) DEFAULT 'Nil',
  `80c_lic_proof` varchar(100) DEFAULT 'Nil',
  `80c_sip_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_sip_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_sip_remarks` varchar(100) DEFAULT 'Nil',
  `80c_sip_proof` varchar(100) DEFAULT 'Nil',
  `80c_mut_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_mut_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_mut_remarks` varchar(100) DEFAULT 'Nil',
  `80c_mut_proof` varchar(100) DEFAULT 'Nil',
  `80c_nps_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_nps_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_nps_remarks` varchar(100) DEFAULT 'Nil',
  `80c_nps_proof` varchar(100) DEFAULT 'Nil',
  `80c_elss_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_elss_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80c_elss_remarks` varchar(100) DEFAULT 'Nil',
  `80c_elss_proof` varchar(100) DEFAULT 'Nil',
  `80ccd1b_nps_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80ccd1b_nps_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80ccd1b_nps_remarks` varchar(100) DEFAULT 'Nil',
  `80ccd1b_nps_proof` varchar(100) DEFAULT 'Nil',
  `80ccg_rgess_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80ccg_rgess_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80ccg_rgess_remarks` varchar(100) DEFAULT 'Nil',
  `80ccg_rgess_proof` varchar(100) DEFAULT 'Nil',
  `80d_medself_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80d_medself_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80d_medself_remarks` varchar(100) DEFAULT 'Nil',
  `80d_medself_proof` varchar(100) DEFAULT 'Nil',
  `80d_medpar_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80d_medpar_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80d_medpar_remarks` varchar(100) DEFAULT 'Nil',
  `80d_medpar_proof` varchar(100) DEFAULT 'Nil',
  `80d_prev_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80d_prev_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80d_prev_remarks` varchar(100) DEFAULT 'Nil',
  `80d_prev_proof` varchar(100) DEFAULT 'Nil',
  `80dd_med_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80dd_med_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80dd_med_remarks` varchar(100) DEFAULT 'Nil',
  `80dd_med_proof` varchar(100) DEFAULT 'Nil',
  `80dd_medsev_act` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80dd_medsev_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80dd_medsev_remarks` varchar(100) DEFAULT 'Nil',
  `80dd_medsev_proof` varchar(100) DEFAULT 'Nil',
  `80ddb_med1_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80ddb_med1_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80ddb_med1_remarks` varchar(100) DEFAULT 'Nil',
  `80ddb_med1_proof` varchar(100) DEFAULT 'Nil',
  `80e_edu_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80e_edu_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80e_edu_remarks` varchar(100) DEFAULT 'Nil',
  `80e_edu_proof` varchar(100) DEFAULT 'Nil',
  `80g_don1_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don1_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don1_remarks` varchar(100) DEFAULT 'Nil',
  `80g_don1_proof` varchar(100) DEFAULT 'Nil',
  `80g_don2_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don2_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don2_remarks` varchar(100) DEFAULT 'Nil',
  `80g_don2_proof` varchar(100) DEFAULT 'Nil',
  `80g_don3_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don3_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don3_remarks` varchar(100) DEFAULT 'Nil',
  `80g_don3_proof` varchar(100) DEFAULT 'Nil',
  `80g_don4_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don4_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don4_remarks` varchar(100) DEFAULT 'Nil',
  `80g_don4_proof` varchar(100) DEFAULT 'Nil',
  `80tta_sav_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80tta_sav_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80tta_sav_remarks` varchar(100) DEFAULT 'Nil',
  `80tta_sav_proof` varchar(100) DEFAULT 'Nil',
  `80u_dis1_act` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80u_dis1_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80u_dis1_remarks` varchar(100) DEFAULT 'Nil',
  `80u_dis1_proof` varchar(100) DEFAULT 'Nil',
  `inter_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `inter_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `inter_remarks` varchar(100) DEFAULT 'Nil',
  `inter_proof` varchar(100) DEFAULT 'Nil',
  `annRent_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `annRent_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `annRent_remarks` varchar(100) DEFAULT 'Nil',
  `annRent_proof` varchar(100) DEFAULT 'Nil',
  `munic_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `munic_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `munic_remarks` varchar(100) DEFAULT 'Nil',
  `munic_proof` varchar(100) DEFAULT 'Nil',
  `unreal_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `unreal_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `unreal_remarks` varchar(100) DEFAULT 'Nil',
  `unreal_proof` varchar(100) DEFAULT 'Nil',
  `housing_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `housing_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `housing_remarks` varchar(100) DEFAULT 'Nil',
  `housing_proof` varchar(100) DEFAULT 'Nil',
  `int_inc_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `int_inc_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `int_inc_remarks` varchar(100) DEFAULT 'Nil',
  `int_inc_proof` varchar(100) DEFAULT 'Nil',
  `lottery_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `lottery_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `lottery_remarks` varchar(100) DEFAULT 'Nil',
  `lottery_proof` varchar(100) DEFAULT 'Nil',
  `letting_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `letting_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `letting_remarks` varchar(100) DEFAULT 'Nil',
  `letting_proof` varchar(100) DEFAULT 'Nil',
  `land_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `land_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `land_remarks` varchar(100) DEFAULT 'Nil',
  `land_proof` varchar(100) DEFAULT 'Nil',
  `other_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `other_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `other_remarks` varchar(100) DEFAULT 'Nil',
  `other_proof` varchar(100) DEFAULT 'Nil',
  `80g_don5_act` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don5_app` decimal(15,2) NOT NULL DEFAULT '0.00',
  `80g_don5_remarks` varchar(100) DEFAULT 'Nil',
  `80g_don5_proof` varchar(100) DEFAULT 'Nil',
  `80g_don6_act` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80g_don6_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80g_don6_remarks` varchar(100) DEFAULT 'Nil',
  `80g_don6_proof` varchar(100) DEFAULT 'Nil',
  `trc_act` decimal(10,2) NOT NULL DEFAULT '0.00',
  `trc_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `trc_remarks` varchar(100) DEFAULT 'Nil',
  `trc_proof` varchar(100) DEFAULT 'Nil',
  `80c_bonds_act` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80c_bonds_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80c_bonds_remarks` varchar(100) DEFAULT 'Nil',
  `80c_bonds_proof` varchar(100) DEFAULT 'Nil',
  `80u_dis2_act` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80u_dis2_app` decimal(10,2) NOT NULL DEFAULT '0.00',
  `80u_dis2_remarks` varchar(100) DEFAULT 'Nill',
  `80u_dis2_proof` varchar(100) DEFAULT 'Nil',
  `status_id` varchar(1) NOT NULL DEFAULT 'A',
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='it declaration';

CREATE TABLE `employee_personal_details` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `employee_gender` varchar(10) CHARACTER SET latin1 NOT NULL,
  `employee_mobile` varchar(12) CHARACTER SET latin1 DEFAULT NULL,
  `employee_dob` date NOT NULL DEFAULT '0000-00-00',
  `father_dob` date DEFAULT '0000-00-00',
  `employee_email` varchar(70) CHARACTER SET latin1 NOT NULL COMMENT 'email id of employee',
  `employee_father_name` varchar(30) CHARACTER SET latin1 NOT NULL,
  `emp_mother_name` varchar(30) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_image` varchar(100) CHARACTER SET latin1 NOT NULL COMMENT 'image url of employee',
  `employee_marital_status` varchar(10) CHARACTER SET latin1 NOT NULL,
  `employee_marriagedate` date DEFAULT '0000-00-00',
  `employee_nationality` varchar(20) CHARACTER SET latin1 DEFAULT 'Indian',
  `employee_international` tinyint(1) DEFAULT '0',
  `employee_blood_group` varchar(20) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_pc` tinyint(1) DEFAULT '0' COMMENT 'physically challenged',
  `employee_pan_proof` varchar(60) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_pan_no` varchar(20) CHARACTER SET latin1 NOT NULL,
  `employee_id_proof_type` varchar(60) CHARACTER SET latin1 DEFAULT 'Nil' COMMENT 'proof type',
  `employee_aadhaar_proof` varchar(60) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_aadhaar_id` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'aadthaar number',
  `employee_id_proof_no` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'proof number',
  `employee_id_proof_expiry` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'proof expiry',
  `employee_bank_name` varchar(60) DEFAULT NULL COMMENT 'bank-details',
  `employee_acc_no` varchar(30) CHARACTER SET latin1 DEFAULT NULL COMMENT 'bank-details',
  `employee_bank_ifsc` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'bank-details',
  `employee_bank_proof` varchar(60) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_bank_branch` varchar(30) CHARACTER SET latin1 DEFAULT NULL COMMENT 'bank-details',
  `employee_id_proof` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_build_name` varchar(70) CHARACTER SET latin1 DEFAULT NULL COMMENT 'addr',
  `employee_area` varchar(50) CHARACTER SET latin1 DEFAULT NULL COMMENT 'addr',
  `employee_pin_code` varchar(6) DEFAULT NULL COMMENT 'addr',
  `employee_city` varchar(50) CHARACTER SET latin1 DEFAULT NULL COMMENT 'addr',
  `employee_street` varchar(50) CHARACTER SET latin1 DEFAULT NULL COMMENT 'addr',
  `employee_state` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `employee_phone` varchar(15) CHARACTER SET latin1 DEFAULT NULL,
  `employee_password` varchar(100) CHARACTER SET latin1 NOT NULL,
  `permanent_emp_bulidname` varchar(70) CHARACTER SET latin1 DEFAULT 'Nil',
  `permanent_emp_area` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `permanent_emp_city` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `permanent_emp_pincode` int(6) DEFAULT '0',
  `permanent_emp_state` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `permanent_emp_country` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_country` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_sslc_school` varchar(100) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_sslc_board` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_ug_institute_name` varchar(100) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_ug_university` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_ug_proof` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `employee_sslc_proof` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `emp_pg_institute_name` varchar(100) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_pg_university` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `employee_pg_proof` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `emp_sslc_marks` decimal(10,2) DEFAULT '0.00',
  `emp_hsc_school` varchar(100) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_hsc_board` varchar(50) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_hsc_marks` varchar(20) CHARACTER SET latin1 DEFAULT 'Nil',
  `emp_hsc_year` int(4) DEFAULT '0',
  `emp_pg_marks` decimal(10,2) DEFAULT '0.00',
  `emp_pg_year_passing` int(4) DEFAULT '0',
  `emp_ug_year_passing` int(4) DEFAULT '0',
  `emp_sslc_year` int(4) DEFAULT '0',
  `employee_hsc_proof` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `employee_pt_adddress` tinyint(1) DEFAULT '0' COMMENT 'is permenant and temporary address are same',
  `emp_ug_marks` decimal(10,2) DEFAULT '0.00' COMMENT 'emp_ug_marks',
  `employee_personal_mobile` varchar(12) CHARACTER SET latin1 DEFAULT NULL,
  `employee_personal_email` varchar(70) CHARACTER SET latin1 DEFAULT NULL,
  `mother_dob` date DEFAULT '0000-00-00',
  `father_mobile` varchar(12) DEFAULT NULL,
  `mother_mobile` varchar(12) DEFAULT NULL,
  `spouse_name` varchar(20) DEFAULT NULL,
  `spouse_mobile` varchar(12) DEFAULT NULL,
  `spouse_dob` date DEFAULT '0000-00-00',
  `emp_ug_degree` varchar(30) DEFAULT NULL,
  `emp_pg_degree` varchar(30) DEFAULT NULL,
  `emp_ug_major_subject` varchar(50) DEFAULT NULL,
  `emp_pg_major_subject` varchar(50) DEFAULT NULL,
  `employee_district` varchar(20) DEFAULT NULL,
  `permanent_emp_dist` varchar(20) DEFAULT NULL,
  `employee_aadhaar_name` varchar(30) DEFAULT NULL,
  `last_login` datetime DEFAULT '0000-00-00 00:00:00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(30) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_emp_id` (`employee_id`),
  CONSTRAINT `employee_personal_details_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='emp personal det';

CREATE TABLE `employee_salary_details` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `slab_id` varchar(20) NOT NULL DEFAULT 'Nil',
  `increment_id` varchar(20) NOT NULL DEFAULT 'CREATION',
  `pf_limit` tinyint(1) NOT NULL DEFAULT '1',
  `esi_limit` tinyint(1) NOT NULL DEFAULT '0',
  `employee_salary_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT 'emp salary',
  `basic` decimal(10,2) DEFAULT '0.00',
  `c_hra` decimal(10,2) DEFAULT '0.00',
  `salary_type` enum('monthly','ctc') DEFAULT NULL,
  `isAnnual` varchar(2) DEFAULT '0',
  `ctc` decimal(10,2) DEFAULT '0.00',
  `ctc_fixed_component` decimal(10,2) DEFAULT '0.00',
  `effects_from` date NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_id` (`employee_id`),
  CONSTRAINT `employee_salary_details_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='emp salary det';

CREATE TABLE `employee_salary_details_history` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `slab_id` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'NA',
  `employee_salary_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT 'emp salary',
  `basic` decimal(10,2) DEFAULT '0.00',
  `c_hra` decimal(10,2) DEFAULT '0.00',
  `salary_type` enum('monthly','ctc') DEFAULT NULL,
  `isAnnual` varchar(2) DEFAULT '0',
  `ctc` decimal(10,2) DEFAULT '0.00',
  `ctc_fixed_component` decimal(10,2) DEFAULT NULL,
  `pf_limit` tinyint(1) NOT NULL DEFAULT '1',
  `esi_limit` tinyint(1) NOT NULL DEFAULT '0',
  `increment_id` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'NA' COMMENT 'increment ID',
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `effects_upto` date NOT NULL DEFAULT '0000-00-00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `employee_salary_details_history_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='emp salary det';

CREATE TABLE `employee_salary_details_shadow` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `slab_id` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'NA',
  `employee_salary_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT 'emp salary',
  `basic` decimal(10,2) DEFAULT '0.00',
  `c_hra` decimal(10,2) DEFAULT '0.00',
  `salary_type` enum('monthly','ctc') DEFAULT NULL,
  `isAnnual` varchar(2) DEFAULT '0',
  `ctc` decimal(10,2) DEFAULT '0.00',
  `ctc_fixed_component` decimal(10,2) DEFAULT NULL,
  `pf_limit` tinyint(1) NOT NULL DEFAULT '1',
  `esi_limit` tinyint(1) NOT NULL DEFAULT '0',
  `increment_id` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'NA' COMMENT 'increment ID',
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_emp_id` (`employee_id`),
  CONSTRAINT `employee_salary_details_shadow_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='emp salary det';

CREATE TABLE `events` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `user` varchar(30) NOT NULL,
  `time` datetime NOT NULL,
  `duration` decimal(5,2) DEFAULT '1.00',
  `title` tinytext NOT NULL,
  `location` text,
  `tag` enum('red','orange','yellow','green','blue','violet','brown','black') DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `exit_reasons` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `exit_id` varchar(10) NOT NULL,
  `reason_code` varchar(50) NOT NULL DEFAULT 'Nil',
  `epf_code` varchar(20) NOT NULL DEFAULT 'Nil',
  `esi_code` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='attendance';

CREATE TABLE `holidays_event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `holiday_id` varchar(20) NOT NULL,
  `category` varchar(20) NOT NULL,
  `branch_id` varchar(20) NOT NULL,
  `title` varchar(40) NOT NULL,
  `start_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `it_slab` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `from_value` int(20) NOT NULL,
  `to_value` int(20) NOT NULL,
  `rate` int(20) NOT NULL,
  `fin_year` varchar(20) NOT NULL,
  `age_group` char(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='profess. tax slab details ';

CREATE TABLE `leave_requests` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `request_id` varchar(20) DEFAULT NULL,
  `employee_id` varchar(30) NOT NULL,
  `from_date` date NOT NULL DEFAULT '0000-00-00',
  `from_half` varchar(20) NOT NULL,
  `to_date` date NOT NULL DEFAULT '0000-00-00',
  `to_half` varchar(20) NOT NULL,
  `duration` float NOT NULL,
  `leave_type` varchar(20) NOT NULL,
  `reason` varchar(300) NOT NULL,
  `status` enum('R','RQ','A','W','C') NOT NULL,
  `admin_reason` varchar(100) DEFAULT NULL,
  `raised_on` date NOT NULL DEFAULT '0000-00-00',
  `approved_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `approved_by` varchar(30) DEFAULT NULL,
  `req_token` varchar(120) DEFAULT NULL,
  `req_token_expiry` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_by` varchar(30) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `message` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(30) NOT NULL,
  `subject` varchar(50) NOT NULL,
  `creator_id` varchar(20) NOT NULL,
  `msg_body` varchar(500) NOT NULL,
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `parent_msg_id` varchar(30) DEFAULT NULL,
  `label` varchar(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `message_recipient` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `recipient_id` varchar(20) NOT NULL,
  `recipent_group_id` varchar(20) DEFAULT NULL,
  `msg_id` varchar(30) NOT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `read_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `conver_id` (`recipient_id`,`msg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `arrears` (
  `employee_id` varchar(30) NOT NULL,
  `month_year` date DEFAULT NULL,
  `processed_on` varchar(20) DEFAULT NULL,
  `basic` decimal(10,2) DEFAULT NULL,
  `c_hra` decimal(10,2) DEFAULT NULL,
  `gross_salary` decimal(10,2) DEFAULT NULL,
  UNIQUE KEY `unique_id` (`employee_id`,`month_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `misc_deduction` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `deduction_id` varchar(50) NOT NULL,
  `remarks` varchar(500) NOT NULL DEFAULT 'Nil',
  `deduction_for` char(1) CHARACTER SET latin1 NOT NULL,
  `dedu_affected_ids` text NOT NULL,
  `deduction_amount` varchar(20) NOT NULL DEFAULT '0|A',
  `dedu_category` varchar(20) NOT NULL DEFAULT 'Nil',
  `deductions_in` varchar(200) NOT NULL DEFAULT 'NA',
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `effects_upto` date NOT NULL DEFAULT '0000-00-00',
  `repetition_count` int(10) NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_group` varchar(2) DEFAULT '0',
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='leave rules';

CREATE TABLE `misc_payments` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `payment_id` varchar(50) CHARACTER SET latin1 NOT NULL,
  `payment_for` char(1) CHARACTER SET latin1 NOT NULL,
  `remarks` varchar(500) NOT NULL DEFAULT 'Nil',
  `pay_affected_ids` text NOT NULL,
  `pay_category` varchar(20) NOT NULL DEFAULT 'Nil',
  `payment_amount` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '0|A',
  `payments_in` varchar(200) NOT NULL DEFAULT 'NA',
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `effects_upto` date NOT NULL DEFAULT '0000-00-00',
  `repetition_count` int(10) NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_group` varchar(2) DEFAULT '0',
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='leave rules';

CREATE TABLE `notification_types` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `notification_type_id` varchar(30) NOT NULL,
  `notification_type` varchar(30) NOT NULL,
  `description` varchar(100) NOT NULL,
  `text` text NOT NULL,
  `action_url` text NOT NULL,
  `screen_action` text,
  PRIMARY KEY (`id`,`notification_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='notifications';

CREATE TABLE `notifications` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `notification_id` varchar(50) NOT NULL,
  `notification_type` varchar(30) NOT NULL,
  `sender_id` varchar(20) NOT NULL DEFAULT 'Nil',
  `receiver_id` varchar(20) NOT NULL DEFAULT 'Nil' COMMENT 'Hotel, Travel, Others',
  `action_id` varchar(20) DEFAULT 'Nil',
  `notif_text` text NOT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `create_date` datetime NOT NULL,
  `read_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`notification_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='salary payment modes';

CREATE TABLE `payroll` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `employee_name` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `month_year` date NOT NULL DEFAULT '0000-00-00',
  `year` int(4) DEFAULT NULL,
  `lop` decimal(10,2) DEFAULT '0.00',
  `alop` decimal(10,2) DEFAULT '0.00',
  `late_lop` decimal(10,2) DEFAULT '0.00',
  `other_leave` decimal(10,2) DEFAULT '0.00',
  `cal_days` decimal(5,2) DEFAULT NULL,
  `worked_days` decimal(5,2) DEFAULT NULL,
  `basic` decimal(10,2) DEFAULT '0.00',
  `c_hra` decimal(10,2) DEFAULT '0.00',
  `m_other_salary` decimal(10,2) DEFAULT '0.00',
  `gross_salary` decimal(10,2) DEFAULT '0.00',
  `c_it` decimal(10,2) DEFAULT '0.00',
  `total_deduction` decimal(10,2) DEFAULT NULL,
  `inc_arrear` decimal(10,2) DEFAULT '0.00',
  `net_salary` decimal(10,2) DEFAULT NULL,
  `is_pay_pending` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'is pay Pending',
  `is_mailSent` tinyint(1) DEFAULT '0',
  `team_id` varchar(20) DEFAULT NULL,
  `department_id` varchar(20) DEFAULT NULL,
  `designation_id` varchar(20) DEFAULT NULL,
  `branch_id` varchar(20) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`employee_id`,`month_year`),
  CONSTRAINT `payroll_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='attendance';

CREATE TABLE `payroll_preview_temp` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `lop` decimal(10,2) DEFAULT '0.00',
  `alop` decimal(10,2) DEFAULT '0.00',
  `late_lop` decimal(10,2) DEFAULT '0.00',
  `other_leave` decimal(10,2) DEFAULT '0.00',
  `cal_days` decimal(5,2) DEFAULT NULL,
  `worked_days` decimal(5,2) DEFAULT NULL,
  `basic` decimal(10,2) DEFAULT '0.00',
  `c_hra` decimal(10,2) DEFAULT '0.00',
  `m_other_salary` decimal(10,2) DEFAULT '0.00',
  `gross_salary` decimal(10,2) DEFAULT '0.00',
  `c_it` decimal(10,2) DEFAULT '0.00',
  `total_deduction` decimal(10,2) DEFAULT '0.00',
  `inc_arrear` decimal(10,2) DEFAULT '0.00',
  `net_salary` decimal(10,2) DEFAULT '0.00',
  `status_flag` char(2) CHARACTER SET latin1 NOT NULL DEFAULT 'A' COMMENT 'A',
  `is_processed` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'set to 1 if payroll is already processed ',
  `is_pay_pending` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Is pay pending',
  `attn_lock` tinyint(1) DEFAULT '0',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_id` (`employee_id`),
  CONSTRAINT `payroll_preview_temp_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='attendance';

CREATE TABLE `payslip_design` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `payslip_id` varchar(10) CHARACTER SET latin1 NOT NULL,
  `payslip_name` varchar(20) DEFAULT NULL,
  `clo_left` varchar(500) CHARACTER SET latin1 NOT NULL,
  `clo_right` varchar(500) CHARACTER SET latin1 DEFAULT NULL,
  `basic_info` varchar(500) CHARACTER SET latin1 DEFAULT NULL,
  `leave_info` varchar(500) CHARACTER SET latin1 DEFAULT NULL,
  `logo` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `themes_id` int(2) DEFAULT NULL,
  `protect_password` varchar(20) DEFAULT NULL,
  `set_active` varchar(2) DEFAULT '0',
  `is_ItSummary` varchar(2) DEFAULT '0',
  `is_mastersalary` varchar(2) DEFAULT '0',
  `color_code` varchar(20) DEFAULT NULL,
  `note` varchar(1000) DEFAULT NULL,
  `payslip_border` varchar(20) DEFAULT NULL,
  `color_header` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `pt_slab` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `pt_city` varchar(100) NOT NULL,
  `eligibility` varchar(10) NOT NULL,
  `from_value` int(20) NOT NULL,
  `to_value` int(20) NOT NULL,
  `rate` int(20) NOT NULL,
  `fin_year` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='profess. tax slab details ';

CREATE TABLE `retirement_benefits` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `r_benefit_id` varchar(30) NOT NULL,
  `salary_heads` varchar(200) NOT NULL,
  `salary_heads_it_exempted` varchar(200) DEFAULT NULL,
  `salary_average_months` int(2) NOT NULL,
  `salary_days` int(2) NOT NULL,
  `round_service_years` char(10) NOT NULL,
  `maximum_amount` decimal(20,2) NOT NULL,
  `updated_by` varchar(20) NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`r_benefit_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='leave rules';

CREATE TABLE `settlements` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `month_year` date NOT NULL DEFAULT '0000-00-00',
  `r_gratuity` decimal(20,2) DEFAULT NULL,
  `r_gratuity_exempted` decimal(20,2) DEFAULT NULL,
  `r_gratuity_remarks` varchar(100) DEFAULT NULL,
  `r_retrenchment` decimal(20,2) DEFAULT NULL,
  `r_retrenchment_exempted` decimal(20,2) DEFAULT NULL,
  `r_retrenchment_remarks` varchar(100) DEFAULT NULL,
  `r_leaveenc` decimal(20,2) DEFAULT '0.00',
  `r_leaveenc_exempted` decimal(20,2) DEFAULT '0.00',
  `r_leaveenc_remarks` varchar(100) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`employee_id`,`month_year`),
  CONSTRAINT `settlements_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employee_work_details` (`employee_id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='settlements';

CREATE TABLE `company_tax_exemptions` (
  `exemption_id` varchar(20) NOT NULL DEFAULT '',
  `title` varchar(30) DEFAULT NULL,
  `exemption_value` varchar(15) DEFAULT NULL,
  `description` tinytext,
  `exempt_type` enum('P','A') DEFAULT NULL,
  `max_exempt_limit` float DEFAULT '0' COMMENT 'max exempt amt per year',
  PRIMARY KEY (`exemption_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `project` (
  `project_id` varchar(20) NOT NULL,
  `project_title` varchar(100) DEFAULT NULL,
  `project_catagory` varchar(50) DEFAULT NULL,
  `description` tinytext,
  `creator` varchar(30) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `client` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `priority` varchar(50) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `hours` varchar(20) DEFAULT NULL,
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `project_assignees` (
  `project_id` varchar(20) NOT NULL DEFAULT '',
  `employee_id` varchar(30) DEFAULT NULL,
  `updated_by` varchar(20) DEFAULT NULL,
  UNIQUE KEY `uqe_project_id` (`project_id`,`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tasks` (
  `project_id` varchar(20) NOT NULL,
  `task_id` varchar(50) NOT NULL DEFAULT '',
  `task_number` varchar(20) NOT NULL,
  `type` varchar(30) DEFAULT NULL,
  `task_name` varchar(50) DEFAULT NULL,
  `task_description` tinytext,
  `task_type` varchar(30) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `hours` varchar(20) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `reviwer` varchar(20) DEFAULT NULL,
  `priority` varchar(50) DEFAULT NULL,
  `percent_done` varchar(4) DEFAULT NULL,
  `creator` varchar(30) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tasks_assignees` (
  `task_id` varchar(20) DEFAULT NULL,
  `employee_id` varchar(30) DEFAULT NULL,
  `updated_by` varchar(20) DEFAULT NULL,
  KEY `tasks_assignees_ibfk_1` (`task_id`),
  CONSTRAINT `tasks_assignees_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`task_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `timesheet` (
  `employee_id` varchar(30) DEFAULT NULL,
  `project_id` varchar(20) DEFAULT NULL,
  `task_id` varchar(20) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `from_time` time DEFAULT NULL,
  `to_time` time DEFAULT NULL,
  `hours` varchar(20) DEFAULT NULL,
  `comments` varchar(100) DEFAULT NULL,
  `status` enum('approved','saved','submitted','disputed') DEFAULT NULL,
  `submitted_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `compensation_requests` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `compoff_id` varchar(20) NOT NULL DEFAULT '',
  `employee_id` varchar(30) NOT NULL,
  `date` date NOT NULL,
  `working_for` varchar(50) NOT NULL,
  `day_count` decimal(5,2) DEFAULT NULL,
  `status` enum('CO','R','2X','RQ') DEFAULT NULL,
  `admin_reason` varchar(100) DEFAULT NULL,
  `is_processed` enum('-1','0','1') DEFAULT '0',
  `approved_on` date DEFAULT NULL,
  `approved_by` varchar(20) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`,`compoff_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

CREATE TABLE `emp_absences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `request_id` varchar(20) DEFAULT NULL,
  `absent_date` date NOT NULL,
  `day_count` decimal(5,2) NOT NULL DEFAULT '0.00',
  `leave_rule_type` varchar(10) NOT NULL,
  `day_type` varchar(10) DEFAULT NULL,
  `reason` varchar(300) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_attn` (`employee_id`,`absent_date`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `weekend` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shift_id` varchar(20) NOT NULL,
  `weeks` char(1) DEFAULT NULL,
  `monday` varchar(5) DEFAULT NULL,
  `tuesday` varchar(5) DEFAULT NULL,
  `wednesday` varchar(5) DEFAULT NULL,
  `thursday` varchar(5) DEFAULT NULL,
  `friday` varchar(5) DEFAULT NULL,
  `saturday` varchar(5) DEFAULT NULL,
  `sunday` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `emailconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `host` varchar(100) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(200) NOT NULL,
  `secure` varchar(20) NOT NULL,
  `port` varchar(10) NOT NULL,
  `active` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `company_details_shadow` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `company_id` varchar(20) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `company_user_name` varchar(20) NOT NULL,
  `current_payroll_month` date NOT NULL,
  `company_type` varchar(20) NOT NULL COMMENT 'company type of incorp',
  `company_logo` varchar(50) NOT NULL COMMENT 'logo url of company',
  `company_build_name` varchar(50) NOT NULL COMMENT 'addr',
  `company_street` varchar(50) NOT NULL COMMENT 'addr',
  `company_area` varchar(30) NOT NULL COMMENT 'addr',
  `company_city` varchar(30) NOT NULL COMMENT 'addr',
  `company_pin_code` int(6) NOT NULL COMMENT 'addr',
  `company_website` varchar(50) NOT NULL,
  `company_state` varchar(50) NOT NULL COMMENT 'addr',
  `company_phone` varchar(12) NOT NULL COMMENT 'phone number',
  `company_mobile` varchar(10) NOT NULL COMMENT 'mobile number',
  `company_email` varchar(40) NOT NULL COMMENT 'email id of company',
  `company_pin` int(4) DEFAULT NULL COMMENT 'the four number . for access',
  `company_pan_no` varchar(20) DEFAULT NULL COMMENT 'pan number',
  `company_tan_pattern` varchar(20) DEFAULT NULL,
  `company_tan_no` varchar(20) DEFAULT NULL COMMENT 'tan number',
  `company_doi` date DEFAULT '0000-00-00',
  `company_cin_no` varchar(25) DEFAULT NULL COMMENT 'cin number',
  `company_epf_pattern` varchar(2) DEFAULT NULL COMMENT 'epf pattrn',
  `company_epf_no` varchar(30) DEFAULT NULL COMMENT 'epf num',
  `company_esi_pattern` varchar(2) DEFAULT NULL COMMENT 'esi pattrn',
  `company_esi_no` varchar(30) DEFAULT NULL COMMENT 'esi num',
  `company_emp_id_suffix` varchar(3) NOT NULL DEFAULT '0' COMMENT 'emp id suff',
  `company_emp_id_prefix` varchar(3) NOT NULL DEFAULT '0' COMMENT 'emp id pref',
  `company_resp1_name` varchar(30) NOT NULL COMMENT 'resp person 1',
  `hr_1username` varchar(20) NOT NULL,
  `company_resp1_desgn` varchar(30) NOT NULL COMMENT 'resp person 1',
  `company_resp1_phone` varchar(20) NOT NULL COMMENT 'resp person 1',
  `company_resp1_email` varchar(40) NOT NULL COMMENT 'resp person 1',
  `company_resp2_name` varchar(30) NOT NULL COMMENT 'resp person 2',
  `company_resp2_desgn` varchar(30) NOT NULL COMMENT 'resp person 2',
  `hr_2username` varchar(20) NOT NULL,
  `company_resp2_phone` varchar(20) NOT NULL COMMENT 'resp person 2',
  `company_resp2_email` varchar(40) NOT NULL COMMENT 'resp person 2',
  `approval_remarks` varchar(50) DEFAULT NULL,
  `info_flag` varchar(20) NOT NULL,
  `leave_based_on` varchar(20) DEFAULT NULL,
  `email_method` enum('phpmail','smtp') DEFAULT NULL,
  `email_notify` enum('yes','no') DEFAULT 'no',
  `salary_days` varchar(2) DEFAULT NULL,
  `attendance_period_sdate` varchar(2) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `letter_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `letter_name` varchar(128) DEFAULT NULL,
  `letter_title` varchar(200) DEFAULT NULL,
  `letter_content` text,
  `enabled` tinyint(1) DEFAULT '1',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `it_properties` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) DEFAULT NULL,
  `value` decimal(10,2) DEFAULT NULL,
  `fin_year` varchar(10) DEFAULT NULL,
  `it_calculation_variable` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `payroll_deduction_breakup` (
  `employee_id` varchar(20) NOT NULL,
  `month_year` date NOT NULL DEFAULT '0000-00-00',
  `year` varchar(10) NOT NULL,
  `c_epf_emp_share` decimal(10,2) DEFAULT NULL,
  `c_epf_elr_share` decimal(10,2) DEFAULT NULL,
  `c_epf_admin_ch` decimal(10,2) DEFAULT NULL,
  `c_esi_emp_share` decimal(10,2) DEFAULT NULL,
  `c_esi_elr_share` decimal(10,2) DEFAULT NULL,
  `c_esi_admin_ch` decimal(10,2) DEFAULT NULL,
  `update_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  UNIQUE KEY `unique_id` (`employee_id`,`month_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `device_sync` (
  `device_id` varchar(50) DEFAULT NULL,
  `sync_dt` datetime DEFAULT NULL,
  `sync_upto` int(5) DEFAULT NULL,
  `roll_over_count` varchar(20) DEFAULT NULL,
  `sync_by` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `device_tcp_listener` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_ip` varchar(30) DEFAULT NULL,
  `listener_ip` varchar(30) DEFAULT NULL,
  `listener_port` varchar(10) DEFAULT NULL,
  `registered_on` date DEFAULT NULL,
  `registered_by` varchar(20) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `device_users` (
  `ref_id` int(20) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(30) NOT NULL,
  `fp1` blob,
  `fp2` blob,
  `fp3` blob,
  `fp4` blob,
  `fp5` blob,
  `status` int(20) DEFAULT '0',
  `pin` int(11) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ref_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `devices` (
  `device_id` int(10) NOT NULL AUTO_INCREMENT,
  `device_name` varchar(20) DEFAULT NULL,
  `IP` varchar(20) DEFAULT NULL,
  `mac_address` varchar(40) DEFAULT NULL,
  `username` varchar(20) DEFAULT NULL,
  `password` varchar(20) DEFAULT NULL,
  `branch_id` varchar(11) DEFAULT NULL,
  `branch_name` varchar(50) DEFAULT NULL,
  `enrollment` int(11) DEFAULT NULL,
  PRIMARY KEY (`device_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `shift_roaster` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) DEFAULT NULL,
  `shift_id` varchar(20) DEFAULT NULL,
  `from_date` date DEFAULT NULL,
  `to_date` date DEFAULT NULL,
  `shift_change_reason` varchar(200) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `employee_biometric` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) NOT NULL,
  `date_time` datetime NOT NULL,
  `ip` varchar(200) DEFAULT NULL,
  `company_id` varchar(20) DEFAULT NULL,
  `event_seq_no` varchar(200) DEFAULT NULL,
  `event_id` varchar(20) DEFAULT NULL,
  `is_manual` enum('0','1') DEFAULT '0',
  `reason` varchar(100) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_id` (`employee_id`,`date_time`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `company_team` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `team_id` varchar(20) DEFAULT NULL,
  `team_name` varchar(50) DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `emp_department_history` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) DEFAULT NULL,
  `promotion_id` varchar(20) DEFAULT NULL,
  `department_id` varchar(20) DEFAULT NULL,
  `effects_from` date DEFAULT NULL,
  `effects_upto` date DEFAULT NULL,
  `department_change_reason` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `emp_job_status_history` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) DEFAULT NULL,
  `status_id` varchar(20) DEFAULT NULL,
  `effects_from` date DEFAULT NULL,
  `effects_upto` date DEFAULT NULL,
  `job_status_change_reason` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `emp_team_history` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) NOT NULL,
  `team_id` varchar(20) NOT NULL,
  `effects_from` date NOT NULL DEFAULT '0000-00-00',
  `effects_upto` date NOT NULL DEFAULT '0000-00-00',
  `team_change_reason` varchar(200) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `attendance_regularization` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) DEFAULT NULL,
  `day` date DEFAULT NULL,
  `regularize_type` varchar(20) DEFAULT NULL,
  `reason_type` varchar(20) DEFAULT NULL,
  `reason` varchar(300) DEFAULT NULL,
  `status` enum('RQ','A','W','R') DEFAULT NULL,
  `admin_reason` varchar(50) DEFAULT NULL,
  `raised_on` datetime DEFAULT NULL,
  `raised_by` varchar(20) DEFAULT NULL,
  `approved_on` date DEFAULT NULL,
  `approved_by` varchar(20) DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(20) DEFAULT NULL,
  `req_token` varchar(120) DEFAULT NULL,
  `req_token_expiry` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `attendance_summary` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) DEFAULT NULL,
  `days` varchar(20) DEFAULT NULL,
  `shift_id` varchar(20) DEFAULT NULL,
  `shift_name` varchar(20) DEFAULT NULL,
  `shift_st_time` varchar(20) DEFAULT NULL,
  `shift_end_time` varchar(20) DEFAULT NULL,
  `shift_hrs` varchar(20) DEFAULT NULL,
  `checkIn` varchar(20) DEFAULT NULL,
  `checkOut` varchar(20) DEFAULT NULL,
  `punches` varchar(200) DEFAULT NULL,
  `tot_worked` varchar(20) DEFAULT NULL,
  `work_hrs` varchar(20) DEFAULT NULL,
  `pay_day` varchar(5) DEFAULT NULL,
  `day_type` varchar(20) DEFAULT NULL,
  `lateIn` varchar(20) DEFAULT NULL,
  `earlyOut` varchar(20) DEFAULT NULL,
  `ot` varchar(20) DEFAULT NULL,
  `late_approved` varchar(2) DEFAULT '0',
  `early_approved` varchar(2) DEFAULT '0',
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_key` (`employee_id`,`days`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `latelop_slab` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from_time` varchar(20) DEFAULT NULL,
  `to_time` varchar(20) DEFAULT NULL,
  `lop_value` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(70) DEFAULT NULL COMMENT 'name of the user',
  `lastname` varchar(70) DEFAULT NULL,
  `username` varchar(30) DEFAULT NULL COMMENT 'username',
  `password` varchar(72) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL COMMENT 'email address',
  `image` varchar(500) DEFAULT NULL COMMENT 'image path',
  `dob` date DEFAULT NULL COMMENT 'date of birth',
  `gender` varchar(50) DEFAULT NULL,
  `created_dt` datetime DEFAULT '0000-00-00 00:00:00' COMMENT 'date',
  `privilage` enum('Master','Manager','Executive','User','hr','employee') NOT NULL DEFAULT 'User' COMMENT 'privilage of the user',
  `isActive` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'user active or not',
  `last_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `p_reset_token` varchar(120) DEFAULT '0',
  `p_reset_expiry` datetime DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `unique_user` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `companies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` varchar(20) DEFAULT NULL,
  `company_name` varchar(100) DEFAULT NULL,
  `company_build_name` varchar(50) DEFAULT NULL,
  `company_street` varchar(50) DEFAULT NULL,
  `company_area` varchar(30) DEFAULT NULL,
  `company_city` varchar(30) DEFAULT NULL,
  `company_pin_code` varchar(6) DEFAULT NULL,
  `company_mobile` varchar(12) DEFAULT NULL,
  `company_email` varchar(70) DEFAULT NULL,
  `company_logo` varchar(50) DEFAULT NULL,
  `company_prefix` varchar(20) DEFAULT NULL,
  `company_suffix` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `appconfig_setting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting` varchar(50) NOT NULL,
  `value` longtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

CREATE TABLE `email_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tplname` varchar(128) NOT NULL,
  `language_id` int(11) NOT NULL DEFAULT '1',
  `subject` text NOT NULL,
  `notification_type` varchar(20) DEFAULT NULL,
  `message` longtext NOT NULL,
  `send` varchar(50) DEFAULT 'Active',
  `core` enum('Yes','No') DEFAULT 'Yes',
  `hidden` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`,`language_id`),
  KEY `tplname` (`tplname`(32))
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


